   #                                                  Titanic Exercise 

   ![titanic](https://userscontent2.emaze.com/images/a5f68f37-6349-4065-a1fc-921cbe7401b2/958230111417e36d6b3c67ffd7bc3494.jpeg)
   #### Practise Pandas

First of all, import the needed libraries.

In [85]:
import numpy as np
import pandas as pd

1. Read in filename and call the variable `titanic`
    - Explore the `titanic` dataset using `info`, `dtypes` & `describe`

In [86]:
titanic = pd.read_csv('data/titanic.csv')
print(titanic.info())
print()
print(titanic.dtypes)
print()
print(titanic.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object
 10  embarked   1307 non-null   object
 11  boat       486 non-null    object
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB
None

pclass         int64
survived       int64
name          object
sex           object
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked      object
boat          object
body         float64
home.dest     object
dtype: object

            pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000
mean      2.294882     0.381971    29.881138     0.498854     0.385027
std       0.837836     0.486055    14.413493     1.041658     0.865560
min       1.000000     0.000000     0.170000     0.000000     0.000000
25%       2.000000     0.000000    21.000000     0.000000     0.000000
50%       3.000000     0.000000    28.000000     0.000000     0.000000
75%       3.000000     1.000000    39.000000     1.000000     0.000000
max       3.000000     1.000000    80.000000     8.000000     9.000000

              fare        body
count  1308.000000  121.000000
mean     33.295479  160.809917
std      51.758668   97.696922
min       0.000000    1.000000
25%       7.895800   72.000000
50%      14.454200  155.000000
75%      31.275000  256.000000
max     512.329200  328.000000

2. Create a separate dataframe with the columns `['name', 'sex', 'age']`, call it `people`

It can be done two ways, do it both!

In [87]:
people = titanic[['name', 'sex', 'age']]
people

                                                 name     sex    age
0                       Allen, Miss. Elisabeth Walton  female  29.00
1                      Allison, Master. Hudson Trevor    male   0.92
2                        Allison, Miss. Helen Loraine  female   2.00
3                Allison, Mr. Hudson Joshua Creighton    male  30.00
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00
...                                               ...     ...    ...
1304                             Zabour, Miss. Hileni  female  14.50
1305                            Zabour, Miss. Thamine  female    NaN
1306                        Zakarian, Mr. Mapriededer    male  26.50
1307                              Zakarian, Mr. Ortin    male  27.00
1308                               Zimmerman, Mr. Leo    male  29.00

[1309 rows x 3 columns]

In [88]:
people = titanic.loc[:, ['name', 'sex', 'age']]
people

                                                 name     sex    age
0                       Allen, Miss. Elisabeth Walton  female  29.00
1                      Allison, Master. Hudson Trevor    male   0.92
2                        Allison, Miss. Helen Loraine  female   2.00
3                Allison, Mr. Hudson Joshua Creighton    male  30.00
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00
...                                               ...     ...    ...
1304                             Zabour, Miss. Hileni  female  14.50
1305                            Zabour, Miss. Thamine  female    NaN
1306                        Zakarian, Mr. Mapriededer    male  26.50
1307                              Zakarian, Mr. Ortin    male  27.00
1308                               Zimmerman, Mr. Leo    male  29.00

[1309 rows x 3 columns]

3. Print the output of `people` showing the first three rows and the last four rows, using `append`,`tail` and `head`

In [89]:
people3 = pd.concat([people.head(3), people.tail(4)])
# df.append was deprecated in pandas version 1.4.0
# people3 = people3.append(people.tail(4))

print(people3)

                                name     sex    age
0      Allen, Miss. Elisabeth Walton  female  29.00
1     Allison, Master. Hudson Trevor    male   0.92
2       Allison, Miss. Helen Loraine  female   2.00
1305           Zabour, Miss. Thamine  female    NaN
1306       Zakarian, Mr. Mapriededer    male  26.50
1307             Zakarian, Mr. Ortin    male  27.00
1308              Zimmerman, Mr. Leo    male  29.00

4. Slice the row from 3 to 9, call it `s_titanic`

In [90]:
s_titanic = titanic[3:9]
s_titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48.0,0,0,19952,26.5500,E12,S,3,NaN,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"

5. Slice the row from 40 to 63 in reverse order, call it `s_titanic_rev`

In [91]:
s_titanic_rev = titanic[63:40:-1]
s_titanic_rev

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
63,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S,4,NaN,"Amenia, ND"
62,1,0,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.1750,E31,S,NaN,NaN,"Amenia, ND"
61,1,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
60,1,0,"Cavendish, Mr. Tyrell William",male,36.0,1,0,19877,78.8500,C46,S,NaN,172.0,"Little Onn Hall, Staffs"
59,1,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,NaN,0,0,17770,27.7208,NaN,C,5,NaN,"New York, NY"
58,1,0,"Case, Mr. Howard Brown",male,49.0,0,0,19924,26.0000,NaN,S,NaN,NaN,"Ascot, Berkshire / Rochester, NY"
57,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.0,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
56,1,1,"Carter, Mr. William Ernest",male,36.0,1,2,113760,120.0000,B96 B98,S,C,NaN,"Bryn Mawr, PA"
55,1,1,"Carter, Miss. Lucile Polk",female,14.0,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
54,1,1,"Carter, Master. William Thornton II",male,11.0,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
53,1,0,"Carrau, Mr. Jose Pedro",male,17.0,0,0,113059,47.1000,NaN,S,NaN,NaN,"Montevideo, Uruguay"
52,1,0,"Carrau, Mr. Francisco M",male,28.0,0,0,113059,47.1000,NaN,S,NaN,NaN,"Montevideo, Uruguay"
51,1,0,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,NaN,NaN,"New York, NY"
50,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.0,0,1,PC 17755,512.3292,B51 B53 B55,C,3,NaN,"Germantown, Philadelphia, PA"
49,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,3,NaN,"Austria-Hungary / Germantown, Philadelphia, PA"
48,1,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53.0,0,0,PC 17606,27.4458,NaN,C,6,NaN,"Washington, DC"
47,1,1,"Calderhead, Mr. Edward Pennington",male,42.0,0,0,PC 17476,26.2875,E24,S,5,NaN,"New York, NY"
46,1,0,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S,NaN,NaN,NaN
45,1,0,"Butt, Major. Archibald Willingham",male,45.0,0,0,113050,26.5500,B38,S,NaN,NaN,"Washington, DC"
44,1,1,"Burns, Miss. Elizabeth Margaret",female,41.0,0,0,16966,134.5000,E40,C,3,NaN,NaN
43,1,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.0,0,0,11813,76.2917,D15,C,8,NaN,"Philadelphia, PA"
42,1,1,"Brown, Mrs. John Murray (Caroline Lane Lamson)",female,59.0,2,0,11769,51.4792,C101,S,D,NaN,"Belmont, MA"
41,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0,0,0,PC 17610,27.7208,B4,C,6,NaN,"Denver, CO"

6. Slice the columns from the starting column to `'parch'`, call it `left_columns`

In [92]:
left_columns = titanic.loc[:, :'parch']
left_columns

,pclass,survived,name,sex,age,sibsp,parch
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2
...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0

7. Slice the columns from `'name'` to `'age'`, call it `middle_columns`

In [93]:
middle_columns = titanic.loc[:, 'name':'age']
middle_columns

                                                 name     sex    age
0                       Allen, Miss. Elisabeth Walton  female  29.00
1                      Allison, Master. Hudson Trevor    male   0.92
2                        Allison, Miss. Helen Loraine  female   2.00
3                Allison, Mr. Hudson Joshua Creighton    male  30.00
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00
...                                               ...     ...    ...
1304                             Zabour, Miss. Hileni  female  14.50
1305                            Zabour, Miss. Thamine  female    NaN
1306                        Zakarian, Mr. Mapriededer    male  26.50
1307                              Zakarian, Mr. Ortin    male  27.00
1308                               Zimmerman, Mr. Leo    male  29.00

[1309 rows x 3 columns]

8. Slice the columns from `'ticket'` to the end, call it `right_columns`

In [94]:
right_columns = titanic.loc[:, 'ticket':]
right_columns

,ticket,fare,cabin,embarked,boat,body,home.dest
0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...
1304,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,315082,7.8750,NaN,S,NaN,NaN,NaN

9. What is the name of the oldest person who died in the Titanic? Was he or she travelling alone or had any family travelling with them?

In order to give an answer to the second question you should find out which columns give you that info. Usually part of your job as a Data Scientist will be get to know the dataset which you are working with. In this case the columns which give you that info are the following: 
        - 'sibsp' Number of Siblings/Spouses Aboard
        - 'parch' Number of Parents/Children Aboard

In [102]:
# 1. 
# titanic.loc[titanic['survived']==0, 'age'].value_counts().sort_index()
max_age_died = titanic.loc[titanic['survived']==0, 'age'].max()
name_max_age_died = titanic.loc[(titanic['survived']==0) & (titanic['age']==max_age_died), 'name'].values
print(f'Name of the oldest person who died in the Titanic: {name_max_age_died}')
print()

# 2. 
print(titanic.loc[titanic['name'].isin(name_max_age_died), ['name', 'sibsp', 'parch']])
name_max_age_died_sibsp = titanic.loc[titanic['name'].isin(name_max_age_died), 'sibsp'].values
name_max_age_died_parch = titanic.loc[titanic['name'].isin(name_max_age_died), 'parch'].values
print(f'{name_max_age_died[0]} was travelling alone (sibsp = {name_max_age_died_sibsp[0]}; parch = {name_max_age_died_parch[0]})')
for i, e in enumerate(name_max_age_died):
    print(f'{e} was travelling with {name_max_age_died_sibsp[i]} sibligs/spouses and {name_max_age_died_parch[i]} parents/children.')

Name of the oldest person who died in the Titanic: ['Svensson, Mr. Johan']

                     name  sibsp  parch
1235  Svensson, Mr. Johan      0      0
Svensson, Mr. Johan was travelling alone (sibsp = 0; parch = 0)
Svensson, Mr. Johan was travelling with 0 sibligs/spouses and 0 parents/children.

10. Create the list of 5 random numbers of rows from 0 to the lenght of the dataframe, call it `rows`

ex. `rows = [3,7,99,52,48]` use `random` library

This list of numbers are random, could be different.

In [96]:
import random

In [97]:
rows = random.sample(range(0, len(titanic)), k=5)
rows

[514, 427, 896, 14, 320]

11. Create the list of three column labels, call it `cols`

In [98]:
cols = random.sample(titanic.columns.tolist(), k=3)
cols

['sibsp', 'sex', 'name']

12. Use both lists `rows` and `cols` to create a new dataframe

In [99]:
# titanic.index
titanic12 = titanic.loc[rows, cols]
titanic12

     sibsp   sex                                  name
514      1  male        Navratil, Master. Edmond Roger
427      1  male             Hamalainen, Master. Viljo
896      0  male                   Johnson, Mr. Alfred
14       0  male  Barkworth, Mr. Algernon Henry Wilson
320      0  male                     Woolner, Mr. Hugh

13. Create a boolean array with the condition of being a woman or a man, using the `sex` column, where **female** is True. Call it `array_fe`

In [100]:
array_fe = (titanic['sex'] == 'female')
array_fe

0        True
1       False
2        True
3       False
4        True
        ...
1304     True
1305     True
1306    False
1307    False
1308    False
Name: sex, Length: 1309, dtype: bool

14. Rename the column `"sex"` to `"gender"` and filter the `titanic` dataframe with the boolean array, call it `woman_titanic`

In [103]:
titanic = titanic.rename(columns={'sex': 'gender'})
woman_titanic = titanic[array_fe]
woman_titanic

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1286,3,1,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,C,NaN,NaN
1290,3,1,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,NaN,NaN,NaN
1300,3,1,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,NaN,NaN,NaN
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN

15. How many woman were younger than 18? Call the variable `minor_wo`

In [105]:
minor_wo = len(woman_titanic[woman_titanic['age']<18])
minor_wo

72

16. How many woman that were less than 18 actually died? Call the variable `dead_wo`

In [106]:
dead_wo = len(woman_titanic[(woman_titanic['age']<18) & (woman_titanic['survived']==0)])
dead_wo

22

17. Drop rows with *Nan* in `titanic` with `how='any'` and print the shape

In [108]:
titanic17 = titanic.dropna(how='any')
print(titanic17.shape)

(0, 14)

18. Drop rows with *Nan* in `titanic` with `how='all'` and print the shape

In [109]:
titanic18 = titanic.dropna(how='all')
print(titanic18.shape)

(1309, 14)

Check in [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html) why the shapes are different.

19. Drop columns in `titanic` with more than 1000 missing values and print the columns remaining

In [121]:
titanic.info()
titanic19 = titanic.dropna(axis=1, thresh=len(titanic)-1000)
print(titanic19.columns)
print()
print(titanic19.shape)
print()
titanic19

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   gender     1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object
 10  embarked   1307 non-null   object
 11  boat       486 non-null    object
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB
Index(['pclass', 'survived', 'name', 'gender', 'age', 'sibsp', 'parch',
       'ticket', 'fare', 'embarked', 'boat', 'home.dest'],
      dtype='object')

(1309, 12)

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,embarked,boat,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,S,2,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,S,11,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,S,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,S,NaN,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,S,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,C,NaN,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,C,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,C,NaN,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,C,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,S,NaN,NaN

20. Calculate the ratio of missing values at the `boat` column.

In [125]:
print(len(titanic[titanic['boat'].isnull()]) / len(titanic))

0.6287242169595111

21.  Group `titanic` by `'pclass'` and aggregate by the columns `age` & `fare`, by `max` and `median` and assign it to `by_class`

22. Print the maximum age in each class from `by_class`

23. Print the median fare in each class from `by_class`

24. Using [`.pivot_table()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html) to count how many women or men survived by class, call it `counted`.

Don't panic and read the documentation!

25. Add a new column with the sum of survived men and women, call it `counted['total']`

26. Sort `counted` by the `'total'` column. In which class the people survived the most?

27. Please, show only the rows using a mask with the following conditions: 
    - They are woman
    - From third class
    - Younger than 30
    - They survived
    
    ¿How many rows fulfill the condition?

28. Now, show only the rows using `.loc` with the following conditions: 
    - They are man
    - From first class
    - Older than 50
    - They died
    
    ¿How many rows fulfill the condition?

29. Print the uniques values at the column `'name'`

In [ ]:
titanic['name'].nunique()

1307

30. Find if was there any `name` repeated at the Titanic?

Hint: There were two people with the same name, who?

31. Using `matplotlib` find the appropriate visualization to show the distribution of the column `'age'`

In [ ]:
import matplotlib.pyplot as plt

32. Using `matplotlib` find the appropriate plot to visualize the column `'gender'`

32b. What if you also plot the column `'gender'` using the function [`countplot`](https://seaborn.pydata.org/generated/seaborn.countplot.html) from the library [`seaborn`](https://seaborn.pydata.org/)?

Remember you have never used `seaborn` before, therefore you should install it before importing it.

In [ ]:
import seaborn as sns

33. Using the function [`catplot`](https://seaborn.pydata.org/generated/seaborn.catplot.html) from the library `seaborn`, find out if the hypothesis _"Women are more likely to survive shipwrecks"_ is true or not.

You should get something like this:

![catplot](./img/catplotgen.png)

34. Using [`kdeplot`]("https://seaborn.pydata.org/generated/seaborn.kdeplot.html") from `seaborn` represent those who not survived distributed by age.<>

Hint: First you should "filter" the `titanic` dataset where the column "survived" is 0, indexing the column `"age"` only.

Arguments you should pass to the function: 

    - color = "red"
    - label = "Not Survived"
    - shade = True
    
You should get something like this:

![kdeplot](./img/kdeplotsur.png)